
 blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Read the documentation
    url: https://askscalify.ai
    about: Please consult the documentation before opening any issues!
  - name: ðŸ™‹ Ask a question
    url: https://discord.gg/Kgw4HpcuYG
    about: Ask questions about how to use Scalify on our Discord server.